### ISSUE TITLE
Discussion on styling

### ISSUE THREAD

**Issue by KristerV** [maxmarcon/live_select#20] opened 2023-03-08 12:44 UTC
- The above input is any old text input generated by Phoenix generators.
- Bottom input is live_select.
- Both are required.
- Only top one shows error when trying to submit, even though the changeset has errors for both fields.

![image](https://user-images.githubusercontent.com/2750622/223716418-1ccdb165-1dcc-4b83-85c8-60d7a24edc10.png)

**Comment by maxmarcon** [comment] 2023-03-08 18:45
Hi. LiveSelect doesn't render form errors, you're supposed to do it yourself if you need to.

Are you rendering an error tag below the input field and it's not showing up? If this is the case, could you please share your heex template and how you're creating the form's changeset? Thanks

**Comment by maxmarcon** [comment] 2023-03-09 12:33
But it's an interesting point... The new phoenix input components display errors automatically right? Which is nice and something the old `Phoenix.HTML.Form` component don't do.

I suspect people will grow accustomed to expect this behavior out of the box, as you did. I could add it to `live_select`, and if someone doesn't want it they can opt-out. Or it could be opt-in, I'm not sure.

**Comment by KristerV** [comment] 2023-03-10 12:21
i'm using this package quite a lot these days and i must admit i find the styling kind of annoying. like the input doesn't conform to core_components and it isn't blank either. so i'm left with overwriting the styles all the time, but it gets kind of messy. i think overall one or the other direction should be chosen.

once you have that the errors can conform to that also. so if the styles are exactly in line with core_components, then may as well have errors rendered in the package. if the styling is blank, then no errors.

i'll open the issue for discussion.

**Comment by maxmarcon** [comment] 2023-03-10 12:36
Thanks for the feedback

>  like the input doesn't conform to core_components and it isn't blank either. so i'm left with overwriting the styles all the time

You can remove the predefined styles entirely by using `style: :none`, and then style everything from scratch. 
Probably easier than using `style: :tailwind` and overriding the single styles using style parameters like: `!style_to_remove style_to_add`, if this is what you mean by "overwriting"

> so if the styles are exactly in line with core_components

would you prefer the default styles to be in line with the ones used by the core components? The core components are using tailwind by default right? We could change the default styles used when setting `style: :tailwind` to be identical to the ones used by core components. That would be a less arbitrary "default style" for tailwind.

In general, I'm interested in feedback about styling because I feel that's one of the trickiest parts to get right. As I got 0 feedback about it so far, I don't know if what I'm doing is ok or totally wrong. So please go ahead and unleash your frustration 😄

**Comment by maxmarcon** [comment] 2023-03-10 22:13
> oh, wasn't aware of this.

Interesting, because it's right at the top of the [styling guide](https://hexdocs.pm/live_select/styling.html). Maybe it should be more prominent then, probably have its own short section in the [module's](https://hexdocs.pm/live_select/LiveSelect.html) docs that refers to the styling guide.

> i couldn't use text_input_extra_class, because sometimes i'm using text_input_class and you i got an error saying i can't have both 🤷 . i think in this situation it would make sense to combine both.

The error message explains why it doesn't make sense to have both: `_extra_class` is to extend the base style, `_class` is to override it completely. If you're using `_extra_class` it means you want to keep the base style and add new stuff to it. If you're using `_class` you want to throw away the base style and replace it with yours. The 2 options are mutually exclusive. Maybe the intent is clearer now.

Regarding your code, thanks for sharing it! I was a bit shocked at first to be honest, I never expected people to write a function component to wrap `live_select` in it 😄 
I now realize that you're doing this because you need to show the error and style the input field accordingly and you want this to happen within the component, as with the core components.

Some feedback:

```elixir
 errors =
      assigns.form.errors
      |> Enum.filter(fn {field_name, _} -> field_name == assigns.field end)
      |> Enum.map(fn {field_name, {msg, _}} -> msg end)
```

you can simplify this part IMO:

```elixir
errors = Enum.map(assigns.form.errors[field_name], &translate_errors/1)
```

where `translate_errors` is the function from `core_components.ex`.

Then to the styles:

```elixir
error_class = if errors != [], do: "border-rose-400 focus:border-rose-400 focus:ring-rose-400/10"

styling_options = if assigns[:text_input_class] do 
   %{text_input_class: assigns[:text_input_class] <>  " #{error_class}")
else
   %{text_input_extra_class: assigns[:text_input_extra_class] <>  " #{error_class}"
end

 assigns =
      assigns
      |> assign(:errors, errors)
      |> assign(:styling_options, styling_options)

    ~H"""
    <.label for={@id}><%= @label %></.label>
    <LiveSelect.live_select
      form={@form}
      field={@field}
      {@styling_options}
      rest={@rest}
    />
    <.error :for={msg <- @errors}><%= msg %></.error>
    """
```

In this way you're either appending the error classes to  `text_input_class` or to `text_input_extra_class`, depending on which one you're using (and if you aren't using any, `text_input_extra_class` is the right place to append to).

I haven't tested the above, but I think it should work 🤞 

Your code and the discussion gave me some ideas:

1. The default for `style: :tailwind` should  probably be identical to the style of the current Phoenix core components
2. Maybe it would be good to have error messages displayed out of the box below the input.
3. There should be a `text_input_error_class` to apply to the text input in case of errors. Again, configurable by the user and identical to core components by default

This is tangential to the topic, but I believe that at some point it would also be good for live select to also accept a `hoenix.HTML.FormField` as `:field` parameter.

**Comment by maxmarcon** [comment] 2023-03-16 15:18
On second thought, instead of overloading the component with even more options/behavior, I'm thinking of walking in the footsteps of the `core_compoents` and show how one can customize it to look and feel like a core component. 

See how you like this approach. 

You first paste this into your `core_components.ex`:

```elixir
 def live_select(%{field: %Phoenix.HTML.FormField{} = field} = assigns) do
    assigns = assign(assigns, :errors, Enum.map(field.errors, &translate_error(&1)))

    ~H"""
    <div phx-feedback-for={@field.name}>
      <.label for={@field.id}><%= @label %></.label>
      <LiveSelect.live_select
        form={@field.form}
        field={@field.field}
        phx-target={assigns[:"phx-target"]}
        allow_clear
        text_input_class={[
          "mt-2 block w-full rounded-lg border-zinc-300 py-[7px] px-[11px]",
          "text-zinc-900 focus:outline-none focus:ring-4 sm:text-sm sm:leading-6",
          "phx-no-feedback:border-zinc-300 phx-no-feedback:focus:border-zinc-400 phx-no-feedback:focus:ring-zinc-800/5",
          "border-zinc-300 focus:border-zinc-400 focus:ring-zinc-800/5",
          @errors != [] && "border-rose-400 focus:border-rose-400 focus:ring-rose-400/10"
        ]}
        option_extra_class="text-sm font-semibold"
      />

      <.error :for={msg <- @errors}><%= msg %></.error>
    </div>
    """
  end
```

and then you can use it like this:

```elixir
 <.live_select field={@form[:my_field]} label="My Lavel" phx-target={@myself}  />
```

*NOTE*: You need to use the latest `live_select` master for this to work, because I had to modify the styling options to accept lists and not only strings

**Comment by maxmarcon** [comment] 2023-03-17 21:30
Hi! Good point. The problem is that live_select doesn't know which label (`location_name`) should correspond to the value (`id`) in the form, so it's using the value itself as the label.

It should work if you pass the right `{label, id}` pair as the set of initially available options:

```elixir
<.live_select 
          field={@form[:location_id]}
          label="Person's location"
          placeholder="Type to search for locations...."
          phx-target={@myself}
         options={[{location_name, @form[:location_id].value}]}
 />
```

The live_select core component above needs to be extended to pass the options:

```elixir
 <LiveSelect.live_select
        form={@field.form}
        ...
        options={@options || []}
/>
...
```

Please try it out and let me know if it works.

**Comment by cblock** [comment] 2023-03-19 20:33
Thanks for your quick reply. I tried out your solution but it didn't work for me. When editing the field I still see the id instead of the name. 
But I'm kind of derailing this thread. So I'll come up with a minimal sample app that reproduces the issue and then open another issue dedicated to this problem. 

As I wrote before: The proposed approach to integrating styling works for me.

**Comment by maxmarcon** [comment] 2023-03-20 06:00
@cblock I just tested with a local app of mine and that works for me, so I'd be very interested in taking a look at your repo with an app that reproduces the issue when it's ready. Thanks!

**Comment by maxmarcon** [comment] 2023-04-02 17:11
Update: I added a [cheatsheet](https://hexdocs.pm/live_select/cheatsheet.html) that shows how to style live_select like a core component, with label and errors.

**Comment by maxmarcon** [comment] 2023-04-04 05:21
Closing this because all the problems mentioned here seem to have been solved, or they're not relevant anymore. Please reopen if you feel otherwise. Thanks

**Closed by maxmarcon** 2023-04-04 05:21 UTC
